// This file is auto-generated by scripts/generate-city-runtime-registry.mjs.
// Regenerate it whenever city packs are added or removed.

import atlantaCityJson from "../../cities/atlanta/city.json";
import atlantaBrandingJson from "../../cities/atlanta/branding.json";
import atlantaSeoJson from "../../cities/atlanta/seo.json";
import atlantaSocialJson from "../../cities/atlanta/social.json";
import atlantaBusinessProfileJson from "../../cities/atlanta/business-profile.json";
import atlantaToursJson from "../../cities/atlanta/tours.json";
import atlantaNarrationJson from "../../cities/atlanta/narration.json";
import atlantaArJson from "../../cities/atlanta/ar.json";
import baltimoreCityJson from "../../cities/baltimore/city.json";
import baltimoreBrandingJson from "../../cities/baltimore/branding.json";
import baltimoreSeoJson from "../../cities/baltimore/seo.json";
import baltimoreSocialJson from "../../cities/baltimore/social.json";
import baltimoreBusinessProfileJson from "../../cities/baltimore/business-profile.json";
import baltimoreToursJson from "../../cities/baltimore/tours.json";
import baltimoreNarrationJson from "../../cities/baltimore/narration.json";
import baltimoreArJson from "../../cities/baltimore/ar.json";
import dcCityJson from "../../cities/dc/city.json";
import dcBrandingJson from "../../cities/dc/branding.json";
import dcSeoJson from "../../cities/dc/seo.json";
import dcSocialJson from "../../cities/dc/social.json";
import dcBusinessProfileJson from "../../cities/dc/business-profile.json";
import dcToursJson from "../../cities/dc/tours.json";
import dcNarrationJson from "../../cities/dc/narration.json";
import dcArJson from "../../cities/dc/ar.json";
import newOrleansCityJson from "../../cities/new-orleans/city.json";
import newOrleansBrandingJson from "../../cities/new-orleans/branding.json";
import newOrleansSeoJson from "../../cities/new-orleans/seo.json";
import newOrleansSocialJson from "../../cities/new-orleans/social.json";
import newOrleansBusinessProfileJson from "../../cities/new-orleans/business-profile.json";
import newOrleansToursJson from "../../cities/new-orleans/tours.json";
import newOrleansNarrationJson from "../../cities/new-orleans/narration.json";
import newOrleansArJson from "../../cities/new-orleans/ar.json";
import phillyCityJson from "../../cities/philly/city.json";
import phillyBrandingJson from "../../cities/philly/branding.json";
import phillySeoJson from "../../cities/philly/seo.json";
import phillySocialJson from "../../cities/philly/social.json";
import phillyBusinessProfileJson from "../../cities/philly/business-profile.json";
import phillyToursJson from "../../cities/philly/tours.json";
import phillyNarrationJson from "../../cities/philly/narration.json";
import phillyArJson from "../../cities/philly/ar.json";
import type { Tour } from "../types";

export type SupportedCityId = "atlanta" | "baltimore" | "dc" | "new-orleans" | "philly";

export const SUPPORTED_CITY_IDS = ["atlanta", "baltimore", "dc", "new-orleans", "philly"] as const;
export const DEFAULT_CITY_ID: SupportedCityId = "philly";

export type CityNarrationVariant = "drive" | "walk";

export type CityNarrationEntry = {
  drive?: string;
  walk?: string;
};

export type CityNarrationPack = {
  catalogByStopId: Record<string, CityNarrationEntry>;
  scriptMapByStopId: Record<string, CityNarrationEntry>;
};

export type CityArEntry = {
  id: string;
  title: string;
  arType: string;
  assetNeeded?: string;
  modelUrl?: string;
  estimatedEffort?: string;
  webModelAvailable?: boolean;
  iosModelAvailable?: boolean;
};

export type CityConfig = {
  id: string;
  name: string;
  shortName: string;
  cityName: string;
  stateCode: string;
  countryCode: string;
  timezone: string;
  slug: string;
  websiteOrigin: string;
  serviceArea: string[];
  defaultMapCenter: { lat: number; lng: number; zoom: number };
  defaultTourId: string;
  launchStatus?: string;
  [key: string]: unknown;
};

export type CityBranding = {
  primary: string;
  secondary: string;
  heroEyebrow: string;
  heroTitle: string;
  heroBody: string;
  [key: string]: unknown;
};

export type CitySeo = {
  homeTitle: string;
  homeDescription: string;
  catalogTitle: string;
  catalogDescription: string;
  homePanelEyebrow: string;
  homePanelTitle: string;
  homePanelBody: string;
  searchImage: string;
  organizationType: string[];
  knowsAbout: string[];
  homePanelHighlights: string[];
  [key: string]: unknown;
};

export type CitySocial = {
  sameAs: string[];
  [key: string]: unknown;
};

export type CityBusinessProfile = {
  businessName: string;
  website: string;
  primaryCategory: string;
  shortDescription: string;
  fullDescription: string;
  [key: string]: unknown;
};

export type CityPackRuntime = {
  city: CityConfig;
  branding: CityBranding;
  seo: CitySeo;
  social: CitySocial;
  businessProfile: CityBusinessProfile;
  tours: Tour[];
  narration: CityNarrationPack;
  ar: Record<string, CityArEntry>;
};

const CITY_REGISTRY: Record<SupportedCityId, CityPackRuntime> = {
  atlanta: {
    city: atlantaCityJson,
    branding: atlantaBrandingJson,
    seo: atlantaSeoJson,
    social: atlantaSocialJson,
    businessProfile: atlantaBusinessProfileJson,
    tours: atlantaToursJson as Tour[],
    narration: atlantaNarrationJson as CityNarrationPack,
    ar: atlantaArJson as Record<string, CityArEntry>
  },
  baltimore: {
    city: baltimoreCityJson,
    branding: baltimoreBrandingJson,
    seo: baltimoreSeoJson,
    social: baltimoreSocialJson,
    businessProfile: baltimoreBusinessProfileJson,
    tours: baltimoreToursJson as Tour[],
    narration: baltimoreNarrationJson as CityNarrationPack,
    ar: baltimoreArJson as Record<string, CityArEntry>
  },
  dc: {
    city: dcCityJson,
    branding: dcBrandingJson,
    seo: dcSeoJson,
    social: dcSocialJson,
    businessProfile: dcBusinessProfileJson,
    tours: dcToursJson as Tour[],
    narration: dcNarrationJson as CityNarrationPack,
    ar: dcArJson as Record<string, CityArEntry>
  },
  new-orleans: {
    city: newOrleansCityJson,
    branding: newOrleansBrandingJson,
    seo: newOrleansSeoJson,
    social: newOrleansSocialJson,
    businessProfile: newOrleansBusinessProfileJson,
    tours: newOrleansToursJson as Tour[],
    narration: newOrleansNarrationJson as CityNarrationPack,
    ar: newOrleansArJson as Record<string, CityArEntry>
  },
  philly: {
    city: phillyCityJson,
    branding: phillyBrandingJson,
    seo: phillySeoJson,
    social: phillySocialJson,
    businessProfile: phillyBusinessProfileJson,
    tours: phillyToursJson as Tour[],
    narration: phillyNarrationJson as CityNarrationPack,
    ar: phillyArJson as Record<string, CityArEntry>
  }
};

export function isSupportedCityId(value: string): value is SupportedCityId {
  return (SUPPORTED_CITY_IDS as readonly string[]).includes(value);
}

export function getCityPackById(cityId: string): CityPackRuntime {
  return CITY_REGISTRY[isSupportedCityId(cityId) ? cityId : DEFAULT_CITY_ID];
}
