create table if not exists public.users (
  id text primary key,
  stripe_customer_id text,
  created_at bigint not null
);

create table if not exists public.payment_orders (
  id bigint generated by default as identity primary key,
  user_id text not null,
  source text not null,
  stripe_payment_intent_id text,
  stripe_checkout_session_id text,
  amount integer not null,
  currency text not null,
  status text not null,
  description text,
  metadata_json text,
  created_at bigint not null,
  updated_at bigint not null
);

create index if not exists payment_orders_user_id_idx on public.payment_orders (user_id);
create unique index if not exists payment_orders_stripe_payment_intent_id_idx
  on public.payment_orders (stripe_payment_intent_id)
  where stripe_payment_intent_id is not null;
create unique index if not exists payment_orders_stripe_checkout_session_id_idx
  on public.payment_orders (stripe_checkout_session_id)
  where stripe_checkout_session_id is not null;

create table if not exists public.entitlements (
  user_id text not null,
  plan_id text not null,
  source text not null,
  status text not null,
  transaction_id text,
  platform text,
  expires_at bigint,
  raw_json text,
  created_at bigint not null,
  updated_at bigint not null,
  primary key (user_id, plan_id)
);

create index if not exists entitlements_user_id_idx on public.entitlements (user_id);

create table if not exists public.iap_receipts (
  id bigint generated by default as identity primary key,
  user_id text not null,
  platform text not null,
  product_id text not null,
  transaction_id text not null unique,
  purchase_token text,
  status text not null,
  raw_json text,
  created_at bigint not null
);

create index if not exists iap_receipts_user_id_idx on public.iap_receipts (user_id);

create table if not exists public.idempotency (
  id text primary key,
  endpoint text not null,
  request_hash text not null,
  response_json text not null,
  status_code integer not null,
  created_at bigint not null
);

create table if not exists public.provider_events (
  id bigint generated by default as identity primary key,
  provider text not null,
  event_id text not null unique,
  event_type text not null,
  payload_json text not null,
  created_at bigint not null
);

create index if not exists provider_events_provider_idx on public.provider_events (provider, created_at desc);

create table if not exists public.deletion_requests (
  id bigint generated by default as identity primary key,
  user_id text not null,
  email text,
  display_name text,
  reason text,
  status text not null,
  requested_at bigint not null,
  resolved_at bigint,
  resolved_by text,
  resolution_note text
);

create index if not exists deletion_requests_user_id_idx on public.deletion_requests (user_id);
create index if not exists deletion_requests_status_idx on public.deletion_requests (status, requested_at desc);
