create table if not exists public.founder_story_posts (
  id bigint generated by default as identity primary key,
  slug text not null unique,
  title text not null,
  excerpt text,
  tags text[] not null default '{}',
  body_markdown text not null default '',
  hero_image text,
  hero_image_alt text,
  video_url text,
  media_caption text,
  gallery jsonb not null default '[]'::jsonb,
  is_published boolean not null default false,
  published_at date,
  created_at bigint not null,
  updated_at bigint not null
);

alter table public.founder_story_posts enable row level security;
revoke all on table public.founder_story_posts from anon, authenticated;

create index if not exists founder_story_posts_public_idx
  on public.founder_story_posts (is_published, published_at desc, id desc);
