create schema if not exists private_content;

revoke all on schema private_content from public;
revoke all on schema private_content from anon;
revoke all on schema private_content from authenticated;

create table if not exists private_content.tours (
  id text primary key,
  slug text unique,
  city_id text not null default 'philly',
  title text not null,
  summary text,
  duration_min integer not null default 0,
  distance_miles numeric(8,2) not null default 0,
  rating numeric(3,2),
  required_plan_id text,
  is_published boolean not null default false,
  sort_order integer not null default 0,
  cover_image_path text,
  cover_image_bucket text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index if not exists private_content_tours_city_idx
  on private_content.tours (city_id, is_published, sort_order, title);

create table if not exists private_content.tour_stops (
  id text primary key,
  tour_id text not null references private_content.tours(id) on delete cascade,
  title text not null,
  description text,
  lat double precision not null,
  lng double precision not null,
  coord_quality text not null default 'approximate' check (coord_quality in ('verified', 'approximate')),
  trigger_radius_m integer not null default 35,
  vertical_offset_m numeric(8,2),
  stop_order integer not null default 0,
  ar_type text,
  ar_priority integer,
  asset_needed text,
  estimated_effort text check (estimated_effort in ('low', 'medium', 'high') or estimated_effort is null),
  street_view jsonb,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index if not exists private_content_tour_stops_tour_idx
  on private_content.tour_stops (tour_id, stop_order);

create table if not exists private_content.tour_stop_scripts (
  stop_id text not null references private_content.tour_stops(id) on delete cascade,
  variant text not null check (variant in ('drive', 'walk')),
  script_text text not null,
  is_published boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  primary key (stop_id, variant)
);

create table if not exists private_content.tour_media_assets (
  id bigint generated by default as identity primary key,
  stop_id text not null references private_content.tour_stops(id) on delete cascade,
  kind text not null check (kind in ('audio', 'model', 'image')),
  variant text,
  platform text,
  bucket text,
  object_path text not null,
  mime_type text,
  is_private boolean not null default true,
  status text not null default 'draft' check (status in ('draft', 'ready', 'archived')),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index if not exists private_content_tour_media_assets_stop_idx
  on private_content.tour_media_assets (stop_id, kind, status);

create unique index if not exists private_content_tour_media_assets_variant_idx
  on private_content.tour_media_assets (stop_id, kind, coalesce(variant, ''), coalesce(platform, ''));
