// Auto-generated by scripts/build-webapp-data.mjs
// Source: src/data/tours.ts AR fields
window.PHILLY_TOURS_AR = {
  "mother-bethel": {
    "id": "mother-bethel",
    "title": "Mother Bethel AME Church",
    "arType": "story_card",
    "assetNeeded": "",
    "modelUrl": "",
    "estimatedEffort": "",
    "webModelAvailable": false,
    "iosModelAvailable": false
  },
  "presidents-house": {
    "id": "presidents-house",
    "title": "President's House / Liberty Bell Center",
    "arType": "story_card",
    "assetNeeded": "",
    "modelUrl": "",
    "estimatedEffort": "",
    "webModelAvailable": false,
    "iosModelAvailable": false
  },
  "johnson-house": {
    "id": "johnson-house",
    "title": "Johnson House",
    "arType": "story_card",
    "assetNeeded": "",
    "modelUrl": "",
    "estimatedEffort": "",
    "webModelAvailable": false,
    "iosModelAvailable": false
  },
  "the-woodlands": {
    "id": "the-woodlands",
    "title": "The Woodlands",
    "arType": "story_card",
    "assetNeeded": "",
    "modelUrl": "",
    "estimatedEffort": "",
    "webModelAvailable": false,
    "iosModelAvailable": false
  },
  "masonic-temple": {
    "id": "masonic-temple",
    "title": "Masonic Temple",
    "arType": "story_card",
    "assetNeeded": "",
    "modelUrl": "",
    "estimatedEffort": "",
    "webModelAvailable": false,
    "iosModelAvailable": false
  },
  "reading-terminal-market": {
    "id": "reading-terminal-market",
    "title": "Reading Terminal Market",
    "arType": "story_card",
    "assetNeeded": "",
    "modelUrl": "",
    "estimatedEffort": "",
    "webModelAvailable": false,
    "iosModelAvailable": false
  },
  "please-touch-museum": {
    "id": "please-touch-museum",
    "title": "Please Touch Museum",
    "arType": "story_card",
    "assetNeeded": "",
    "modelUrl": "",
    "estimatedEffort": "",
    "webModelAvailable": false,
    "iosModelAvailable": false
  },
  "shofuso": {
    "id": "shofuso",
    "title": "Shofuso Japanese House & Garden",
    "arType": "story_card",
    "assetNeeded": "",
    "modelUrl": "",
    "estimatedEffort": "",
    "webModelAvailable": false,
    "iosModelAvailable": false
  },
  "alpha-phi-alpha": {
    "id": "alpha-phi-alpha",
    "title": "Alpha Phi Alpha - 42nd & Chestnut",
    "arType": "story_card",
    "assetNeeded": "",
    "modelUrl": "",
    "estimatedEffort": "",
    "webModelAvailable": false,
    "iosModelAvailable": false
  },
  "delta-sigma-theta": {
    "id": "delta-sigma-theta",
    "title": "Delta Sigma Theta - 40th & Market",
    "arType": "story_card",
    "assetNeeded": "",
    "modelUrl": "",
    "estimatedEffort": "",
    "webModelAvailable": false,
    "iosModelAvailable": false
  },
  "phi-beta-sigma": {
    "id": "phi-beta-sigma",
    "title": "Phi Beta Sigma - 44th & Market",
    "arType": "story_card",
    "assetNeeded": "",
    "modelUrl": "",
    "estimatedEffort": "",
    "webModelAvailable": false,
    "iosModelAvailable": false
  },
  "iota-phi-theta": {
    "id": "iota-phi-theta",
    "title": "Iota Phi Theta - Temple Greek Row",
    "arType": "story_card",
    "assetNeeded": "",
    "modelUrl": "",
    "estimatedEffort": "",
    "webModelAvailable": false,
    "iosModelAvailable": false
  },
  "the-palestra": {
    "id": "the-palestra",
    "title": "The Palestra",
    "arType": "story_card",
    "assetNeeded": "",
    "modelUrl": "",
    "estimatedEffort": "",
    "webModelAvailable": false,
    "iosModelAvailable": false
  },
  "hampton-park": {
    "id": "hampton-park",
    "title": "Allen Iverson's Hampton Park Courts",
    "arType": "story_card",
    "assetNeeded": "",
    "modelUrl": "",
    "estimatedEffort": "",
    "webModelAvailable": false,
    "iosModelAvailable": false
  },
  "joe-frazier": {
    "id": "joe-frazier",
    "title": "Joe Frazier's Gym (Cloverlay)",
    "arType": "story_card",
    "assetNeeded": "",
    "modelUrl": "",
    "estimatedEffort": "",
    "webModelAvailable": false,
    "iosModelAvailable": false
  },
  "overbrook": {
    "id": "overbrook",
    "title": "Overbrook High School",
    "arType": "story_card",
    "assetNeeded": "",
    "modelUrl": "",
    "estimatedEffort": "",
    "webModelAvailable": false,
    "iosModelAvailable": false
  },
  "library-company": {
    "id": "library-company",
    "title": "Library Company of Philadelphia",
    "arType": "story_card",
    "assetNeeded": "",
    "modelUrl": "",
    "estimatedEffort": "",
    "webModelAvailable": false,
    "iosModelAvailable": false
  },
  "athenaeum": {
    "id": "athenaeum",
    "title": "Athenaeum of Philadelphia",
    "arType": "story_card",
    "assetNeeded": "",
    "modelUrl": "",
    "estimatedEffort": "",
    "webModelAvailable": false,
    "iosModelAvailable": false
  },
  "free-library": {
    "id": "free-library",
    "title": "Free Library - Central Parkway",
    "arType": "story_card",
    "assetNeeded": "",
    "modelUrl": "",
    "estimatedEffort": "",
    "webModelAvailable": false,
    "iosModelAvailable": false
  },
  "blockson": {
    "id": "blockson",
    "title": "Charles L. Blockson Collection",
    "arType": "story_card",
    "assetNeeded": "",
    "modelUrl": "",
    "estimatedEffort": "",
    "webModelAvailable": false,
    "iosModelAvailable": false
  }
};
