// Auto-generated by scripts/build-webapp-data.mjs
// Source: src/data/tours.ts AR fields
window.PHILLY_TOURS_AR = {
  "founders-demo-route-welcome-plaza": {
    "id": "founders-demo-route-welcome-plaza",
    "title": "Welcome Plaza",
    "arType": "story_card",
    "assetNeeded": "",
    "modelUrl": "",
    "estimatedEffort": "",
    "webModelAvailable": false,
    "iosModelAvailable": false
  },
  "founders-demo-route-story-corner": {
    "id": "founders-demo-route-story-corner",
    "title": "Story Corner",
    "arType": "none",
    "assetNeeded": "",
    "modelUrl": "",
    "estimatedEffort": "",
    "webModelAvailable": false,
    "iosModelAvailable": false
  },
  "founders-demo-route-compass-garden": {
    "id": "founders-demo-route-compass-garden",
    "title": "Compass Garden",
    "arType": "none",
    "assetNeeded": "",
    "modelUrl": "",
    "estimatedEffort": "",
    "webModelAvailable": false,
    "iosModelAvailable": false
  },
  "founders-demo-route-finish-arch": {
    "id": "founders-demo-route-finish-arch",
    "title": "Finish Arch",
    "arType": "story_card",
    "assetNeeded": "",
    "modelUrl": "",
    "estimatedEffort": "",
    "webModelAvailable": false,
    "iosModelAvailable": false
  }
};
