// Auto-generated by scripts/build-webapp-data.mjs
// Source: content/blog/*.md
window.PHILLY_TOURS_BLOG = [
  {
    "slug": "2026-05-12-in-person-tour-guide-launch",
    "title": "In-Person Tour Guide Launch",
    "publishedAt": "2026-05-12",
    "excerpt": "The new guided route checkout is live on the webapp, making it easier to book a hosted Philadelphia storytelling experience.",
    "tags": [
      "launch",
      "guided tours",
      "webapp"
    ],
    "bodyHtml": "<p>We just turned on <strong>in-person tour guide checkout</strong> in the Philly Tours webapp.</p>\n<p>This makes it easier for schools, visitors, and community groups to turn a self-guided route into a hosted walk with a live guide, coordinated pacing, and the matching map pack for the group.</p>\n<h2>What is included</h2>\n<ul><li>A guided version of the selected route</li><li>Coordinated pacing for the group</li><li>The matching Google map pack for navigation and handoff</li></ul>\n<h2>Why this matters</h2>\n<p>The webapp has always been strong for planning, previewing stops, and exploring the story structure of a route. Guided checkout closes the loop by making it simple to move from browsing into a real hosted tour.</p>\n<p>We are also improving the internal notification flow so Founders Threads gets alerted as soon as one of these bookings is purchased.</p>",
    "bodyText": "We just turned on in-person tour guide checkout in the Philly Tours webapp.\nThis makes it easier for schools, visitors, and community groups to turn a self-guided route into a hosted walk with a live guide, coordinated pacing, and the matching map pack for the group.\nWhat is included\nA guided version of the selected route\nCoordinated pacing for the group\nThe matching Google map pack for navigation and handoff\nWhy this matters\nThe webapp has always been strong for planning, previewing stops, and exploring the story structure of a route. Guided checkout closes the loop by making it simple to move from browsing into a real hosted tour.\nWe are also improving the internal notification flow so Founders Threads gets alerted as soon as one of these bookings is purchased."
  },
  {
    "slug": "2026-05-01-story-routes-update",
    "title": "Story Routes Update",
    "publishedAt": "2026-05-01",
    "excerpt": "A quick look at how the route pages are evolving, from richer stop previews to stronger planning tools before you arrive on site.",
    "tags": [
      "product",
      "routes",
      "storytelling"
    ],
    "bodyHtml": "<p>The route pages are becoming more useful before the walk even starts.</p>\n<p>We are shaping them into a place where visitors can understand the arc of a route, preview key stops, and decide whether they want a self-guided experience or a live guide.</p>\n<h2>Recent improvements</h2>\n<ul><li>Better route context and story framing</li><li>Clearer stop order and map previews</li><li>More visible guided-tour purchase moments</li></ul>\n<h2>What comes next</h2>\n<p>We want each route page to feel like a compact field guide: part editorial story, part planning surface, and part launch point into the mobile experience.</p>\n<p>That means more updates around blog content, route curation notes, and founder commentary directly inside the webapp.</p>",
    "bodyText": "The route pages are becoming more useful before the walk even starts.\nWe are shaping them into a place where visitors can understand the arc of a route, preview key stops, and decide whether they want a self-guided experience or a live guide.\nRecent improvements\nBetter route context and story framing\nClearer stop order and map previews\nMore visible guided-tour purchase moments\nWhat comes next\nWe want each route page to feel like a compact field guide: part editorial story, part planning surface, and part launch point into the mobile experience.\nThat means more updates around blog content, route curation notes, and founder commentary directly inside the webapp."
  }
];
