// Auto-generated by scripts/build-webapp-data.mjs
// Sources: src/data/narrationCatalog.ts, src/data/narrationScriptMap.ts
window.PHILLY_TOURS_NARRATION = {
  "catalogByStopId": {
    "founders-demo-route-welcome-plaza": {
      "drive": "",
      "walk": ""
    },
    "founders-demo-route-story-corner": {
      "drive": "",
      "walk": ""
    },
    "founders-demo-route-compass-garden": {
      "drive": "",
      "walk": ""
    },
    "founders-demo-route-finish-arch": {
      "drive": "",
      "walk": ""
    }
  },
  "scriptMapByStopId": {
    "founders-demo-route-welcome-plaza": {
      "drive": "Welcome Plaza is ahead. This is a public demo stop used to show route narration without exposing production tour writing.",
      "walk": "You are now at Welcome Plaza. This short sample narration exists only to demonstrate the public app flow."
    },
    "founders-demo-route-story-corner": {
      "drive": "Story Corner is ahead. In the private system, stops like this would carry richer historical narration and media.",
      "walk": "You are now at Story Corner. This placeholder script shows where premium story content would normally appear."
    },
    "founders-demo-route-compass-garden": {
      "drive": "Compass Garden is ahead. Use this demo stop to test navigation, progress, and guided movement in the public repo.",
      "walk": "You are now at Compass Garden. The live production narration library is intentionally not stored in this public repository."
    },
    "founders-demo-route-finish-arch": {
      "drive": "Finish Arch is ahead. This closes the sample route and marks the end of the public demo catalog.",
      "walk": "You are now at Finish Arch. Real tour scripts, oral histories, and premium writing are kept outside the public repository."
    }
  }
};
