// Auto-generated by scripts/build-webapp-data.mjs
// Source: .env browser-safe values
window.PHILLY_TOURS_CONFIG = {
  "supabaseUrl": "https://inqopeveskosnfjhuein.supabase.co",
  "supabaseAnonKey": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImlucW9wZXZlc2tvc25mamh1ZWluIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzQyNzc2OTQsImV4cCI6MjA4OTg1MzY5NH0.Wlobb-yPJok7ma25XsIIoJE6QWggnlGMETtTT8qpwqc",
  "newsletterTable": "newsletter_subscribers",
  "syncServerUrl": "https://api.philly-tours.com",
  "cloudflareTurnstileSiteKey": "0x4AAAAAACyMqxdcuuRnVfpL",
  "googleMapsProjectUrl": "https://www.google.com/maps/d/edit?mid=1ea-gv-cbR6gROsZXeYitu86fokfFGsw&ll=39.964376774626835%2C-75.17661126896972&z=13",
  "googleMapsJsApiKey": "AIzaSyDwFyoYPbK6nDCXG0acVnjM2871wLXux7U",
  "googleMapsMapId": "9cad125dd87aa9d11e16ecb2",
  "inPersonTourGuidePriceCents": "",
  "inPersonTourGuideLabel": "In-person tour guide",
  "iosAppStoreUrl": "",
  "androidPlayStoreUrl": ""
};
