// Auto-generated by scripts/build-webapp-data.mjs
// Source: source-safe placeholder values. Deploy output injects browser-safe env values.
window.PHILLY_TOURS_CONFIG = {
  "supabaseUrl": "",
  "supabaseAnonKey": "",
  "newsletterTable": "newsletter_subscribers",
  "syncServerUrl": "",
  "cloudflareTurnstileSiteKey": "",
  "googleMapsProjectUrl": "",
  "googleMapsJsApiKey": "",
  "googleMapsMapId": "",
  "inPersonTourGuidePriceCents": "",
  "inPersonTourGuideLabel": "In-person tour guide",
  "iosAppStoreUrl": "",
  "androidPlayStoreUrl": ""
};
