// Auto-generated by scripts/build-webapp-data.mjs
// Source: src/data/tours.ts
window.PHILLY_TOURS_DATA = [
  {
    "id": "founders-demo-route",
    "title": "Founders Demo Route",
    "durationMin": 48,
    "distanceMiles": 1.8,
    "rating": 4.7,
    "stops": [
      {
        "id": "founders-demo-route-welcome-plaza",
        "title": "Welcome Plaza",
        "description": "Sample stop for the public demo catalog. This is not part of the private production tour set.",
        "lat": 39.9526,
        "lng": -75.1652,
        "coordQuality": "approximate",
        "triggerRadiusM": 35,
        "modelUrl": "",
        "audioUrl": ""
      },
      {
        "id": "founders-demo-route-story-corner",
        "title": "Story Corner",
        "description": "A placeholder point showing how a stop can appear in the route flow without exposing premium narration or archives.",
        "lat": 39.9551,
        "lng": -75.1608,
        "coordQuality": "approximate",
        "triggerRadiusM": 35,
        "modelUrl": "",
        "audioUrl": "",
        "arType": "none"
      },
      {
        "id": "founders-demo-route-compass-garden",
        "title": "Compass Garden",
        "description": "Demo-only waypoint for map, compass, and progress surfaces in the public repository.",
        "lat": 39.9498,
        "lng": -75.1589,
        "coordQuality": "approximate",
        "triggerRadiusM": 35,
        "modelUrl": "",
        "audioUrl": "",
        "arType": "none"
      },
      {
        "id": "founders-demo-route-finish-arch",
        "title": "Finish Arch",
        "description": "Closing sample stop. Real route sequencing, research, and media are kept outside the public repo.",
        "lat": 39.9482,
        "lng": -75.1636,
        "coordQuality": "approximate",
        "triggerRadiusM": 35,
        "modelUrl": "",
        "audioUrl": ""
      }
    ]
  }
];
